### ISSUE TITLE
Video element support

### ISSUE THREAD

**Issue by Koenvh1** [Fenny/Castjs#10]
The TODO in the readme, what does it mean precisely?

For quite some time now I have been looking for a simple way to stream content from a video or audio element to a Google Cast device, keeping the controls of the video/audio element as is, only using them to control the Google Cast device instead. Is this also what you had in mind with CastJS?

**Comment by Fenny** [comment]
Hi @Koenvh1 ,

Yeah that is exactly what I was planning to add next.
```javascript
new Castjs($('video'));
```

So when you add an html element instead of an url, the library would just add the cast icon in the corner of the video player ( if casting is supported ) and use the video element controls to seek / pause / play / mute the chromecast.

I have some other running projects at the moment, maybe in december I will add this feature.

But for now you have to create custom controls like I showed here:

https://fenny.github.io/Castjs/demo/

**Comment by Koenvh1** [comment]
Marvellous. Then I will keep following your updates. 
Best of luck 👍
